name: website-mdx
on:
  pull_request:
    paths: [website/**]

jobs:
  generate-website-mdx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: "."
      - name: generate plugin docs
        run: go run ./cmd/waypoint docs -website-mdx
      - name: generate cli docs
        run: go run ./tools/gendocs
      - run: rm waypoint-restore.db.lock; git status
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          path: website/
          name: website

  check-website-mdx:
    runs-on: ubuntu-latest
    needs:
      - generate-website-mdx
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: website/
          name: website
      - run: git status
      - run: cd ./website; npm i -g npm@latest; npm install
      - run: cd ./website; npx --no-install next-hashicorp format
      - run: |
          if ! git diff --exit-code website/content > /dev/null; then
            echo "Website directory has unstaged mdx changes. This is because you have modified doc strings"
            echo "that must be reflected in the website. Run the following make command:"
            echo
            echo "make gen/website-mdx"
            echo
            echo "And then validate that the corresponding website pages look acceptable."
            git status
            exit 1
          fi

permissions:
  contents: read
